name: 自动同步原仓库更新

# 触发条件：每天定时执行 + 手动触发
on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时检测一次（可调整频率）
  workflow_dispatch:  # 允许手动触发（在GitHub界面操作）

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：拉取当前仓库代码
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整历史，避免合并冲突

      # 步骤2：配置Git身份（用于提交合并记录）
      - name: 配置Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 步骤3：添加原仓库为上游stream（如果未配置）
      - name: 关联原仓库
        run: |
          git remote add upstream https://github.com/jaywcjlove/linux-command.git || true
          # 上面的地址需与你git remote -v中显示的upstream地址一致

      # 步骤4：拉取原仓库最新代码
      - name: 拉取原仓库更新
        run: git fetch upstream

      # 步骤5：合并原仓库代码到本地master分支
      - name: 合并原仓库更新
        run: |
          git checkout master# 切换到你的主分支（如果是main请修改）
          git merge upstream/master  # 合并原仓库的master分支（与原仓库保持一致）

      # 步骤6：推送到你的fork仓库
      - name: 推送到自己的仓库
        run: git push origin master  # 推送到你的origin仓库的master分支